Update members.blade.php
april-knights/Squire pull request #67
Opened 2022-06-02 15:19 UTC by Gryph667

Adding banner maybe

2022-06-27 01:16 UTC, LeoVerto requested changes
Same problem as #66, in fact it would probably be nicer to move these changes over to that one.

2022-06-27 01:16 UTC, LeoVerto commented on resources/views/division/members.blade.php
> +             alt="{{ $div->name }} Banner" title="{{ $div->name }} Banner"
Unclosed img tag.

2022-06-27 02:12 UTC, Gryph667 commented on resources/views/division/members.blade.php
> +             alt="{{ $div->name }} Banner" title="{{ $div->name }} Banner"
Changed both, committed to branch.

2022-07-07 19:54 UTC, Gryph667 commented
Merging

2022-07-07 19:56 UTC, merged